import React, {Component} from 'react';
import { Redirect } from 'react-router-dom';

import * as env from '../../env'
import style from '../Login/style.css'

export class Checkout extends Component {
    constructor(props) {
        super(props);  
        
        let _fields = {};

        //TODO refactor this and 'const neededFields' from componentDidMount() in this component
        let namesOfInputFields = Object.keys(env.order) //get only the key names which are supposed to be displayed (eg. the user doesnt input the orderdate (its autogenerated), so we dont show it)
            .filter(key => typeof env.order[key]["fieldname"] !== 'undefined')
            .forEach(key => _fields[key]='');

        this.state = {
            fields: {
                ..._fields, //are you a wizard
            },
            issues: [],
            redirect: null, //will become <Redirect to='/'/>
        }

        this.handleSubmit = this.handleSubmit.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }

    async componentDidMount() {
        let userToken = localStorage.getItem(env.tokenCookieName);

        if(!userToken) return;
        const requestParams = {
            method: 'GET',
            headers: {
                'Authorization': 'Bearer ' + userToken,
                'Content-Type': 'application/x-www-form-urlencoded',
            }
        };
        let userInfo = await (await fetch(env.host + env.apiUserInfo, requestParams)).json();
        
        const neededFields = Object.keys(userInfo) //key array {0: key1, 1: key2} and so on
            .filter(key => env.order[key]) // * Take only keys which exist in env.order
            .reduce( (obj, key) => {obj[key]=userInfo[key]; return obj;}, {}); //turn {0: key1} array into {key1: value} object
        
            const {name, surname} = env.userRegister;
        this.setState(prevState => ({
            fields: {
                ...prevState.fields,
                ...neededFields,
                [env.order.contractingAuthority.name]: [ userInfo[name], userInfo[surname] ].join(' '),
            }
        }));
    }

    handleChange(e) { //generic handleChange (uses "name" property of <input/>)
        e.persist();
        this.setState(prevState => ({
                fields: {
                    ...prevState.fields,
                    [e.target.name]: e.target.value 
                }
        }))
    }

    async handleSubmit(e) {
        e.preventDefault();
        
        let _issues = [];
        this.setState({issues:_issues});
        let appendIssue = issue => _issues.push(issue);        
        const fieldContents = this.state.fields;
        
        let emptyFields = Object.keys(fieldContents)
            .filter(key => !fieldContents[key])
            .filter(key => key!==env.order.discountCouponId.name);

        emptyFields.forEach(emptyField => appendIssue(env.errorMessageStrings.fieldIsEmpty(env.order[emptyField].fieldname)));

        if(_issues.length > 0) {
            this.setState({issues:_issues});
            return;
        }
        
        const body = {
                ...fieldContents,
                key: localStorage.getItem(env.guidCookieName),
            orderDate: (new Date).toISOString(),
        }

        const fetchParams = {
            method: 'POST',

            }
        
        const response = await fetch(env.host+env.apiOrder+'?'+env.objToQueryString(body), fetchParams);

        const responseCode = await response.status;
        console.log(responseCode);
        if(responseCode === 204) { //TODO post order returns 500 but adds the product, I don't know why
            appendIssue(env.errorMessageStrings.fetchFailed);
            this.setState({issue: _issues});
            return;
        }

        appendIssue("Zamówienie złożone pomyślnie!");
        this.setState(
            {
            issue: _issues,
            /*redirect: <Redirect to='/'/>,*/
        });

        localStorage.clear(env.guidCookieName);
    }

    render() {
        const inputFields = Object.keys(this.state.fields).map( key => {
            const {name, placeholder, fieldname, type} = env.order[key];
            return <input key={name} type={type} name={name} placeholder={placeholder} onChange={this.handleChange} value={this.state.fields[key] || ""}/>
        });

        return(
            <div className={style.login}>
                {this.state.redirect}
                <h1>Składanie zamówienia</h1>
                <form onSubmit={this.handleSubmit} className={style.login__form}>
                    {inputFields}
                    <input type="submit" value="Zamów" className={style.buyButton}/>
                </form>
                {this.state.issues.map( issue => <div>{issue}</div>)}
            </div>
        );
    }
}

